[package]
name = "joto_constants"
version = "0.2.0"
description = "Constants for interoperation between US Customary and SI units."
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version = "1.64"